#!/bin/bash
echo "Fix Ydfs"
if [ -e /root/.ydfs/fixydfs ]
then
ls /root/.ydfs/fixydfs |while read file
  do
    echo /root/.ydfs/fixydfs/$file >> /tmp/run-fixes
    bash /root/.ydfs/fixydfs/$file &
  done
fi
echo
