#!/bin/sh

  if [ -e nss/build.sh ]
  then
	echo "Inside $0"
  	cp $HOME_DIBAB/config/nss/Linux.mk nss/coreconf/Linux.mk || exit
	cd nss 
#  ./build.sh -v --opt --system-sqlite --system-nspr --disable-tests || exit 11

  make -j1 BUILD_OPT=1                  \
  NSPR_INCLUDE_DIR=/$HOME_DIBAB/$ARCH/include/nspr  \
  SQLITE_LIB_DIR=/$HOME_DIBAB/$ARCH/lib  \
  USE_SYSTEM_ZLIB=1                   \
  ZLIB_LIBS=-lz                       \
  NSS_ENABLE_WERROR=0                 \
  $([ $ARCH = x86_64 ] && echo USE_64=1) || exit $?

  install -v -m755 -d $PREFIX/include/nss                   
  cp -v -RL ../dist/public/nss/* $PREFIX/include/nss 
  cp -v -RL ../dist/private/nss/* $PREFIX/include/nss     
  cp -fRL ../dist/Linux*/* $PREFIX 

  cp -fR $HOME/ydfs/packages-$ARCH/sqlite-src-*/* /
  touch ../buildok-$ARCH 
  exit 0

  fi
