#!/bin/sh
if [ -e xbmc-xrandr.c ]
then
    mkdir kodi-build
    cd kodi-build
    cmake -DCMAKE_INSTALL_PREFIX=$HOME/$ARCH \
    -DCMAKE_INSTALL_LIBDIR=$HOME/$ARCH/lib \
    -DENABLE_EVENTCLIENTS=ON \
    -DLIRC_DEVICE=/run/lirc/lircd \
    -DENABLE_INTERNAL_FFMPEG="no" \
    -DWITH_FFMPEG="yes" \
    ../project/cmake || exit $?

     make || exit $?
     make install || exit $?
     DESTDIR=$HOME/ydfs/packages-$ARCH/$MYDIR make install
  if [ "$MODULE" = "opkg" ]
  then
    cd $HOME/ydfs/packages-$ARCH/$MYDIR
    $HOME_DIBAB/scripts/make_opkg || exit $?
  fi
     touch buildok-$ARCH
     exit 0 
fi 
