#!/bin/bash
PKG=$1
SHORT=${PKG:0:2}
#echo "1 $1 PKG $PKG SHORT $SHORT"
install -d $HOME/archpkg
cd $HOME/archpkg
URL2=https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/$1/trunk/PKGBUILD
URL1=https://raw.githubusercontent.com/archlinux/svntogit-community/packages/$1/trunk/PKGBUILD

OPTION=" --no-check-certificate" 
OPTION=" -q --no-check-certificate" 
if [ ! -e $HOME/archpkg/$PKG ]
then
	echo "Get $PKG"
wget $OPTION "$URL1" -O $HOME/archpkg/$PKG || \
	wget $OPTION "$URL2" -O $HOME/archpkg/$PKG || \
	ERROR=1
fi

ls -l $HOME/archpkg/$PKG
test -s $HOME/archpkg/$PKG
if [ $? = 1 ]
then
 echo "Error, delete $HOME/archpkg/$PKG which is empty"
 rm $HOME/archpkg/$PKG
 exit 1
fi


echo "DBG source $HOME/archpkg/$PKG"
source $HOME/archpkg/$PKG

bash

for i in ${!source[*]}
do 
 echo ${source[i]}
 break
done
