#!/bin/sh

export ARCH=`uname -m`
[ "$ARCH" = "i686" ] && ARCH=x86 # FIXME : enable sed in busybox
echo -n "Creating "
for device in `ls /sys/class/block/`
do
	if [ ! -e /dev/$device ]
	then
		echo -n "$device "
		mknod /dev/$device b `cat /sys/class/block/$device/dev | cut -d ':' -f1` `cat /sys/class/block/$device/dev | cut -d ':' -f2`
	fi
done
echo

install -d /media/dibab

[ -e /dibab/boot/options/liveusb  ] && echo "LiveUsb mode" && sleep 5

if [ ! -e /dibab/boot/options/livecd ] # look only on cdrom drive
then
echo "search into hard/usb disks"
mkdir /disk
for device in `ls /sys/class/block/`
do

	if [ ! -e /dev/$device ]
	then
		echo "Creating $device"
		mknod /dev/$device b `cat /sys/class/block/$device/dev | cut -d ':' -f1` `cat /sys/class/block/$device/dev | cut -d ':' -f2`
	fi
	echo $device | grep sd >/dev/null || continue
	echo -n "$device ? "
        if [ -e /dibab/boot/options/liveusb  ]
        then
          find /sys |grep $device|grep usb >/dev/null || continue
          echo "is removable"
          #[ -e /sys/class/block/$device/removable ] || continue
          #grep 1 /sys/class/block/$device/removable >/dev/null || continue
        fi
	/ntfs-3g  /dev/$device /disk 2>/dev/null || mount /dev/$device /disk -o rw 2>/dev/null || continue
	# Wubi
	[ -e /disk/$DISTRONAME/install/installation.iso ] && mount /disk/$DISTRONAME/install/installation.iso /media/dibab && break
	#[ -e /disk/$DISTRONAME/install/dibab-"$ARCH".iso ] && mount /disk/$DISTRONAME/install/dibab-"$ARCH".iso /media/dibab && break
	#[ -e /disk/$DISTRONAME/install/test.iso ] && mount /disk/$DISTRONAME/install/test.iso /media/dibab && break
	# live usb mount read write
	if [ -e /disk/modules/$ARCH.squashfs ]
        then
          umount /disk 
          /ntfs-3g /dev/$device /media/dibab 2>/dev/null || mount /dev/$device /media/dibab -o rw && break
        fi
        umount /disk
done
fi

if [ ! -e /media/dibab/modules/$ARCH.squashfs ]
then
	echo -n "livecd ? "
	for CDROM in sr0 sr1 sr2 sr3 sr4 sr5 sr6
	do
	  [ -e /dev/$CDROM ] && mount /dev/$CDROM /media/dibab && echo "$CDROM" && install -d /var/dibab/boot/media/cdrom/$CDROM && break
	done
fi

