#!/bin/bash
date=$(zenity --calendar --date-format="%Y-%m-%d")

array=(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23)
hour=$(zenity --entry --title "Hour : " --text "${array[@]}" --text "Select the current hour")
# echo "Hour : $hour"

array=(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59)
minute=$(zenity --entry --title "Minute : " --text "${array[@]}" --text "Select the current minute")
# echo "Minute : $minute"

echo "Date : $date $hour:$minute:00"
date --set="$date $hour:$minute:00"

hwclock -w
