#!/bin/sh
if [ -e xbmc-xrandr.c ]
then

#    OLDPWD=$PWD
#    cd /home/linuxconsole2018/ydfs/src/xbmc-17.6-Krypton/kodi-build/build/libdvd/src/dvdread/
#	ACLOCAL_FLAGS="-I $HOME/$ARCH/share/aclocal " && ACLOCAL="aclocal -I $HOME/opkg/share/aclocal $ACLOCAL_FLAGS " autoreconf -vif
#	cd $OLDPWD

    mkdir kodi-build
    cd kodi-build
    [ ! -e libdvdcss.tar.gz ] && wget https://github.com/xbmc/libdvdcss/archive/1.4.1-Leia-Alpha-3.tar.gz && mv 1.4.1-Leia-Alpha-3.tar.gz libdvdcss.tar.gz
    [ ! -e libdvdnav.tar.gz ] && wget https://github.com/xbmc/libdvdnav/archive/6.0.0-Leia-Alpha-3.tar.gz && mv 6.0.0-Leia-Alpha-3.tar.gz libdvdnav.tar.gz
    [ ! -e libdvdread.tar.gz ] && wget https://github.com/xbmc/libdvdread/archive/6.0.0-Leia-Alpha-3.tar.gz && mv 6.0.0-Leia-Alpha-3.tar.gz libdvdread.tar.gz
    [ ! -e 3.1.11-Krypton-17.5.tar.gz ] && wget https://github.com/xbmc/FFmpeg/archive/3.1.11-Krypton-17.5.tar.gz
	pwd

	
    CXX="g++ -I$PWD/build/include/" cmake -DCMAKE_INSTALL_PREFIX=$HOME/$ARCH \
    -Dlibdvdcss_URL="$PWD/libdvdcss.tar.gz" \
    -Dlibdvdnav_URL="$PWD/libdvdnav.tar.gz" \
    -Dlibdvdread_URL="$PWD/libdvdread.tar.gz" \
    -DFFMPEG_URL="$PWD/3.1.11-Krypton-17.5.tar.gz" \
    -DCMAKE_INSTALL_LIBDIR=$HOME/$ARCH/lib \
    -DENABLE_EVENTCLIENTS=ON \
    -DENABLE_INTERNAL_FFMPEG=OFF \
    -DENABLE_OPTICAL=OFF \
    -DLIRC_DEVICE=/run/lirc/lircd \
    ../project/cmake 

    sed -i -e 's/PKG_CHECK_MODULES(DVDREAD, dvdread >= 5.0.3)//' build/libdvd/src/dvdnav/configure
    sed -i -e 's/PKG_CHECK_MODULES(CSS, $CSS_REQUIRES)//' build/libdvd/src/dvdread/configure

    CXX="g++ -I$PWD/build/include/" cmake -DCMAKE_INSTALL_PREFIX=$HOME/$ARCH \
    -Dlibdvdcss_URL="$PWD/libdvdcss.tar.gz" \
    -Dlibdvdnav_URL="$PWD/libdvdnav.tar.gz" \
    -Dlibdvdread_URL="$PWD/libdvdread.tar.gz" \
    -DFFMPEG_URL="$PWD/3.1.11-Krypton-17.5.tar.gz" \
    -DCMAKE_INSTALL_LIBDIR=$HOME/$ARCH/lib \
    -DENABLE_EVENTCLIENTS=ON \
    -DENABLE_INTERNAL_FFMPEG=OFF \
    -DENABLE_OPTICAL=OFF \
    -DLIRC_DEVICE=/run/lirc/lircd \
    ../project/cmake 

    sed -i -e 's/PKG_CHECK_MODULES(DVDREAD, dvdread >= 5.0.3)//' build/libdvd/src/dvdnav/configure
    sed -i -e 's/PKG_CHECK_MODULES(CSS, $CSS_REQUIRES)//' build/libdvd/src/dvdread/configure

    CXX="g++ -I$PWD/build/include/" cmake -DCMAKE_INSTALL_PREFIX=$HOME/$ARCH \
    -Dlibdvdcss_URL="$PWD/libdvdcss.tar.gz" \
    -Dlibdvdnav_URL="$PWD/libdvdnav.tar.gz" \
    -Dlibdvdread_URL="$PWD/libdvdread.tar.gz" \
    -DFFMPEG_URL="$PWD/3.1.11-Krypton-17.5.tar.gz" \
    -DCMAKE_INSTALL_LIBDIR=$HOME/$ARCH/lib \
    -DENABLE_EVENTCLIENTS=ON \
    -DENABLE_INTERNAL_FFMPEG=OFF \
    -DENABLE_OPTICAL=OFF \
    -DLIRC_DEVICE=/run/lirc/lircd \
    ../project/cmake || exit $?

     VERBOSE=1 make || exit $?
     make install || exit $?
     DESTDIR=$HOME/ydfs/packages-$ARCH/$MYDIR make install
  if [ "$MODULE" = "opkg" ]
  then
    cd $HOME/ydfs/packages-$ARCH/$MYDIR
    $HOME_DIBAB/scripts/make_opkg || exit $?
  fi
     touch buildok-$ARCH
     exit 0 
fi 
