#!/bin/bash
install -d $HOME/archpkg
cd $HOME/archpkg
URL=https://projects.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages
URL2=https://projects.archlinux.org/svntogit/packages.git/plain/trunk/PKGBUILD?h=packages
PKG=$1
SHORT=${PKG:0:2}
URL3=https://aur.archlinux.org/packages/$SHORT/$1/PKGBUILD

if [ ! -e $HOME/archpkg/$PKG ]
then
wget --no-check-certificate "$URL""/""$1" -O $HOME/archpkg/$PKG || wget --no-check-certificate "$URL2""/""$1" -O $HOME/archpkg/$PKG || wget --no-check-certificate "$URL3" -O $HOME/archpkg/$PKG || ERROR=1
fi

test -s $HOME/archpkg/$PKG
if [ $? = 1 ]
then
 echo "Error, delete $HOME/archpkg/$PKG which is empty"
 rm $HOME/archpkg/$PKG
 exit 1
fi

source $HOME/archpkg/$PKG

for i in ${!source[*]}
do 
 echo ${source[i]}
 break
done
