#!/bin/bash
install -d $HOME/archpkg
cd $HOME/archpkg
URL=https://gitlab.archlinux.org/archlinux/packaging/packages/$1/-/raw/main/PKGBUILD?ref_type=heads
URL2=https://gitlab.archlinux.org/archlinux/packaging/packages/$1/-/raw/main
PKG=$1
SHORT=${PKG:0:2}
#[ -e $PKG ] && rm $PKG
if [ ! -e $HOME/archpkg/$PKG ]
then
wget --no-check-certificate -q "$URL""/""$1""/-/raw/main/PKGBUILD?ref_type=heads" -O $HOME/archpkg/$PKG || ERROR=1
fi

. $HOME/archpkg/$PKG

for i in ${!source[*]}
do 
 if [ $i -gt 0 ]
 then
	echo ${source[i]}
	echo 'https://gitlab.archlinux.org/archlinux/packaging/packages/cinnamon-desktop/-/raw/main/config.patch?ref_type=heads' > $HOME/.archpatches
	echo $URL2/${source[i]}?ref_type=heads >> $HOME/.archpatches
 fi
done
