#!/bin/sh

[ ! -e /etc/hosts ] && echo "127.0.0.1	localhost" > /etc/hosts

[ ! -e /dev/ppp ] && mknod /dev/ppp c 108 0
[ ! -e /usr/sbin/pppd ] && ln -s /usr/bin/pppd /usr/sbin/pppd
 
ifconfig lo 127.0.0.1

if [ ! -e $HOME_DIBAB/$ARCH/etc/smb.conf ]
then
  echo 'netbios name = LinuxConsole' > $HOME_DIBAB/$ARCH/etc/smb.conf
  echo 'client min protocol = NT1' >> $HOME_DIBAB/$ARCH/etc/smb.conf
fi

#Bug NetworkManager sometimes don't start dhcpd on eth0
#if [ -e /usr/sbin/NetworkManager ]
#then
cat >> /etc/NetworkManager/NetworkManager.conf << "EOF"
[main]
plugins=keyfile
EOF
  NetworkManager --log-level=ERR
#else
  sleep 1 # waiting loading kernel module
  [ -e /ydfs/boot/options/livecd ] && echo -n " waiting .. " && sleep 3 # LiveCD could be very slow
  ETH=`/ydfs/detect/eth0`
  if [ "$ETH" != "" ]
  then
    echo "Start dhcp on $ETH"
    ifconfig $ETH up > /var/log/eth0.log
    udhcpc -i $ETH -t 5 -q -S -s /etc/udhcpc/simple.script >/dev/null 2>/dev/null &
  else
    echo "No network card was found"
  fi
#fi
