#!/bin/bash
install -d $HOME/archpkg
cd $HOME/archpkg
URL=https://raw.githubusercontent.com/archlinux/svntogit-packages/packages
PKG=$1
SHORT=${PKG:0:2}
URL3=https://aur.archlinux.org/packages/$SHORT/$1/PKGBUILD
URL4=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$PKG

#[ -e $PKG ] && rm $PKG
if [ ! -e $HOME/archpkg/$PKG ]
then
wget --no-check-certificate -q "$URL""/""$1""/trunk/PKGBUILD" -O $HOME/archpkg/$PKG || wget --no-check-certificate -q "$URL3" -O $HOME/archpkg/$PKG || wget --no-check-certificate "$URL4" -O $HOME/archpkg/$PKG || ERROR=1
fi

. $HOME/archpkg/$PKG

for i in ${!source[*]}
do 
	SOURCE=${source[i]}
	echo "DEBUG SOURCE : $SOURCE"
	FILE=${source[i]}
	echo ${source[i]} |grep '::' && SOURCE=https:`echo ${source[i]} | cut -d':' -f8`
	echo "DEBUG SOURCE : $SOURCE"
 if [ $i -gt 0 ]
 then
#	echo ${source[i]}
	PATCHURL=https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/$PKG/trunk/$SOURCE
	PATCHURL2=https://raw.githubusercontent.com/archlinux/svntogit-community/packages/$PKG/trunk/$SOURCE
	PATCHURL3=https://aur.archlinux.org/cgit/aur.git/plain/$SOURCE?h=$PKG
	PATCHURL4=$SOURCE
	install -d /tmp/patches
	wget $PATCHURL -O /tmp/patches/$FILE || wget $PATCHURL2 -O /tmp/patches/$FILE || wget $PATCHURL3 -O /tmp/patches/$FILE || wget $PATCHURL4 -O /tmp/patches/$FILE 
 fi
 #break
done
