#!/bin/sh
if [ "$1"  = "" ]
then
  echo $0 needs directory as argument
  exit 1
fi
. ./config.ini
cd $HOME//packages/$1 || exit $?
find | while read file 
do
  echo $file
  [ -f "/"$file ] && echo "Remove /$file" && rm "/"$file
  [ -h "/"$file ] && echo "Remove /$file" && rm "/"$file
done

cd home/*
find | while read file 
do
  [ -f "$HOME//modules/"$file ] && echo "Remove $HOME//modules/"$file && rm "$HOME//modules/"$file
  [ -h "$HOME//modules/"$file ] && echo "Remove $HOME//modules/"$file && rm "$HOME//modules/"$file
done

rm -fR $HOME//packages/$1
rm $HOME//src/$1-*/*.done
