#!/bin/sh

if [ ! -e $HOME/.config/libfm/libfm.conf ]
then
install -d  $HOME/.config/libfm
echo "
[config]
single_click=0
use_trash=1
confirm_del=1
advanced_mode=0
si_unit=0
force_startup_notify=1
backup_as_hidden=1
no_usb_trash=0
no_child_non_expandable=0
show_internal_volumes=0
terminal=lxterminal
archiver=file-roller
thumbnail_local=0
thumbnail_max=2048
[ui]
big_icon_size=48
small_icon_size=24
pane_icon_size=24
thumbnail_size=128
show_thumbnail=1
" > $HOME/.config//libfm/libfm.conf
fi

if [ -e /usr/share/applications/kde4 ] 
then
ls /usr/share/applications/kde4 | while read file
do
  echo "move $file"
  mv /usr/share/applications/kde4/$file /usr/share/applications
done
rmdir /usr/share/applications/kde4
fi

if [ ! -e $HOME/.config/lxpanel/default/panels/panel ]
then
  install -d $HOME/.config/lxpanel/default/panels/
  if [ -e /usr/share/applications/midori.desktop ]
  then
	WEB=/usr/share/applications/midori.desktop
  else
	WEB=qupzilla.desktop 
	#WEB=/share/applications/firefox.desktop
  fi
  echo "
# lxpanel config file. Manually editing is not recommended.
# build from /ydfs/config/lxde

Global {
    edge=bottom
    allign=left
    margin=0
    widthtype=percent
    width=100
    height=26
    transparent=0
    tintcolor=#000000
    alpha=0
    autohide=0
    heightwhenhidden=2
    setdocktype=1
    setpartialstrut=1
    usefontcolor=1
    fontcolor=#ffffff
    background=1
    backgroundfile=/usr/share/lxpanel/images/background.png
    iconsize=24
}

Plugin {
    type = space
    Config {
        Size=2
    }
}

Plugin {
    type = menu
    Config {
        image=/usr/share/lxpanel/images/my-computer.png
        system {
        }
        separator {
        }
        item {
            command=run
        }
        separator {
        }
        item {
            image=gnome-logout
            command=logout
        }
    }
}

Plugin {
    type = space
    Config {
        Size=4
    }
}

Plugin {
    type = launchbar
    Config {
        Button {
            id=/usr/share/applications/pcmanfm.desktop
        }
        Button {
            id=$WEB
        }
    }
}

Plugin {
    type = wincmd
    Config {
        image=window-manager
        Button1=iconify
        Button2=shade
        Toggle=0
    }
}

Plugin {
    type = space
    Config {
        Size=4
    }
}

Plugin {
    type = pager
}

Plugin {
    type = space
    Config {
        Size=4
    }
}

Plugin {
    type = taskbar
    expand=1
    Config {
        tooltips=1
        IconsOnly=0
        ShowAllDesks=0
        UseMouseWheel=1
        UseUrgencyHint=1
        FlatButton=0
        MaxTaskWidth=150
        spacing=1
        GroupedTasks=0
    }
}

Plugin {
    type = cpu
}

Plugin {
    type = tray
}

Plugin {
    type = dclock
    Config {
        ClockFmt=%R
        TooltipFmt=%A %x
        BoldFont=0
        IconOnly=0
    }
}

Plugin {
    type = volumealsa
}

Plugin {
    type = batt
    Config {
        HideIfNoBattery=0
        AlarmCommand=zenity --warning --text="Battery low !"
        AlarmTime=10
        BackgroundColor=black
        BorderWidth=4
        ChargingColor1=#28f200
        ChargingColor2=#22cc00
        DischargingColor1=#ffee00
        DischargingColor2=#d9ca00
        Size=16
    }
}

" > $HOME/.config/lxpanel/default/panels/panel
if [ ! -e $HOME/.config/lxpanel/LXDE ]
then
  ln -s $HOME/.config/lxpanel/default $HOME/.config/lxpanel/LXDE ||cp -fR $HOME/.config/lxpanel/default $HOME/.config/lxpanel/LXDE # Fat filesystem
fi
fi

if [ ! -e $HOME/.config/lxpanel/default/config ]
then
  install -d $HOME/.config/lxpanel/default/
echo "
 [Command]
 FileManager=pcmanfm %s
 Terminal=lxterminal
 Logout=killall lxsession
" > $HOME/.config/lxpanel/default/config
fi

if [ ! -e $HOME/.config/pcmanfm/LXDE/pcmanfm.conf ]
then
  install -d $HOME/.config/pcmanfm/LXDE
echo "
[config]
bm_open_method=0
su_cmd=xdg-su -c '%s'

[volume]
mount_on_startup=1
mount_removable=1
autorun=1

[desktop]
wallpaper_mode=3
wallpaper_common=1
wallpaper=/etc/ydfs.png
desktop_bg=#ffffff
desktop_fg=#ffffff
desktop_shadow=#000000
desktop_font=Sans 12
show_wm_menu=0
sort_type=0
sort_by=7

[ui]
always_show_tabs=0
max_tab_chars=32
win_width=640
win_height=480
splitter_pos=150
side_pane_mode=1
view_mode=0
show_hidden=0
sort_type=0
sort_by=0
" > $HOME/.config/pcmanfm/LXDE/pcmanfm.conf
  ln -s $HOME/.config/pcmanfm/LXDE $HOME/.config/pcmanfm/default ||cp -fR $HOME/.config/pcmanfm/LXDE $HOME/.config/pcmanfm/default # Fat filesystems
fi
