#!/bin/bash
MESSAGE="You must be root to configure parental logoff"
[ "$LANG" = "fr_FR.UTF8" ] && MESSAGE="Vous devez être root pour configurer le contrôle parental"
[ "$USER" != "root" ] && zenity --info --text="$MESSAGE" && exit 0
LIST_USERS=""
while read -r file
do
  echo $file | grep linuxconsole2019 && continue
  LIST_USERS="$LIST_USERS FALSE $file"
done <<<$(ls /home)
echo $LIST_USERS

if [ "$LANG" = "fr_FR.UTF8" ]
then
USER=$(zenity  --list --hide-header --width=400 --height=200  --text "Utilisateur pour lequel configurer le controle parental :" --radiolist  --column "Choix" --column "Type" $LIST_USERS)
[ "$USER" = "" ] && exit 0
VALUE=$(zenity --scale --text="Temps maximum par jour pour $USER"  --value=2 --min-value=1 --max-value=24)
else
USER=$(zenity  --list --hide-header --width=400 --height=200  --text "Choose user for parental logoff :" --radiolist  --column "Choice" --column "Type" $LIST_USERS)
[ "$USER" = "" ] && exit 0
VALUE=$(zenity --scale --text="Max time, in hour for $USER"  --value=2 --min-value=1 --max-value=24)
fi

install -d /home/$USER/.config/
chown $USER /home/$USER/.config/
echo $VALUE > /home/$USER/.config/plogoff
