version: '3'
services:
    linuxconsole32-2024:
        image: yledoare/ydfs-2.10:32-bits
        volumes:
            - $HOME/iso:/home/linuxconsole2024/iso
        environment:
            BUILDYDFS: "fast"
            SLEEPTIME: 1
        security_opt:
            - seccomp:unconfined
