#!/bin/bash
install -d $HOME/archpkg
cd $HOME/archpkg
URL=URL=https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/
PKG=$1
SHORT=${PKG:0:2}
[ -e $PKG ] && rm $PKG
if [ ! -e $HOME/archpkg/$PKG ]
then
wget --no-check-certificate "$URL""/""$1""/trunk/PKGBUILD" -O $HOME/archpkg/$PKG || ERROR=1
fi

test -s $HOME/archpkg/$PKG 
if [ $? = 1 ]
then
 echo "Error, delete $HOME/archpkg/$PKG which is empty"
 rm $HOME/archpkg/$PKG
 exit 1
fi

source $HOME/archpkg/$PKG

for i in ${!source[*]}
do 
 echo ${source[i]}
 break
done
