#!/bin/bash
install -d $HOME/archpkg
cd $HOME/archpkg
URL0=https://raw.githubusercontent.com/archlinux/svntogit-community/packages/$1/trunk/PKGBUILD
URL1=https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/$1/trunk/PKGBUILD
URL=https://raw.githubusercontent.com/archlinux/svntogit-community/packages/
URL2=https://projects.archlinux.org/svntogit/packages.git/plain/trunk/PKGBUILD?h=packages/
URL2=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=
PKG=$1
SHORT=${PKG:0:2}
URL3=https://aur.archlinux.org/packages/$SHORT/$1/PKGBUILD
URL4=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$PKG

OPTION=" --no-check-certificate" 
OPTION=" -q --no-check-certificate" 
if [ ! -e $HOME/archpkg/$PKG ]
then
wget $OPTION "$URL1" -O $HOME/archpkg/$PKG || wget $OPTION "$URL""/""$1" -O $HOME/archpkg/$PKG || wget $OPTION "$URL2""$1" -O $HOME/archpkg/$PKG || wget $OPTION "$URL3" -O $HOME/archpkg/$PKG || wget $OPTION "$URL4" -O $HOME/archpkg/$PKG || ERROR=1
fi

test -s $HOME/archpkg/$PKG
if [ $? = 1 ]
then
 echo "Error, delete $HOME/archpkg/$PKG which is empty"
 rm $HOME/archpkg/$PKG
 exit 1
fi

source $HOME/archpkg/$PKG

for i in ${!source[*]}
do 
 echo ${source[i]}
 break
done
