#!/bin/bash
install -d $HOME/archpkg
cd $HOME/archpkg
URL=https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/
PKG=$1
SHORT=${PKG:0:2}
#[ -e $PKG ] && rm $PKG
if [ ! -e $HOME/archpkg/$PKG ]
then
wget --no-check-certificate -q "$URL""/""$1""/trunk/PKGBUILD" -O $HOME/archpkg/$PKG || ERROR=1
fi

. $HOME/archpkg/$PKG

for i in ${!source[*]}
do 
 if [ $i -gt 0 ]
 then
#	echo ${source[i]}
	echo $URL/$PKG/trunk/${source[i]} >> $HOME/.archpatches
 fi
 #break
done
