#!/bin/bash
install -d $HOME/archpkg
cd $HOME/archpkg
URL=https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/
PKG=$1
[ -e $PKG ] && rm $PKG
wget -q "$URL""/""$1""/trunk/PKGBUILD" -O $HOME/archpkg/$PKG || exit 1

source $HOME/archpkg/$PKG

for i in ${!source[*]}
do 
 echo ${source[i]}
 break
done
